### ISSUE TITLE
how to use code

### ISSUE THREAD

**Issue by justlovebarbecue** [dips4717/gcn-cnn#5]
Hi thanks for sharing your code! Could you please provide a to-do list for more details about running code? such as which folder should contain the pre-computed data, and the required packages information.

Thanks in advance!

**Comment by justlovebarbecue** [comment]
hi, I meet the following error when I tried to run triplet-based training. It happened in line71 of dataloader_triplet.py


...
s/dataloader_triplet.py", line 71, in pickle_load
    data = pickle.load(pf)
_pickle.UnpicklingError: invalid load key, '\x00'.


I guess it may be caused by versions of some packages? do you have any clue about it?

Thanks!!

**Comment by dips4717** [comment]
Hi @justlovebarbecue, that loading the pickle file. Can you please put a complete traceback of the error?
It might be issue with the python version you are using, are you python3.x?

**Comment by justlovebarbecue** [comment]
Hi @dips4717 , I finally solved this problem. It is caused my some data transferring issue. Now, the downloaded data can be used!

Thanks!
